<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2017-04-09T21:51:46+02:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      api_keys.google.maps
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'api_keys' => [
        'google' => [
            'maps' => 'AIzaSyAgK3I3M0KwFp4K6hARCD3VWVn4K4ID_tM',
        ],
    ],
];
