<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2017-02-01T13:57:55+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.name
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'Factorian',
        ],
    ],
];
